[package]
name = "mcomp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
clap = "4.3.17"
glob = "0.3.1"
lazy_static = "1.4.0"
regex = "1.9.1"
rhai = "1.15.1"
walkdir = "2.3.3"
